INSERT INTO "Customer" VALUES(108,'Literature & Fiction','pmurphy0','vo60rgCqWDqB','ahoward0@eepurl.com');
INSERT INTO "Customer" VALUES(109,'Literature & Fiction','anichols1','XLWcPBaKCAr','rperry1@bbb.org');
INSERT INTO "Customer" VALUES(110,'Accounting & Finance','greed2','vNDCjr','nlopez2@independent.co.uk');
INSERT INTO "Customer" VALUES(111,'Accounting & Finance','rbanks3','lAY6nckAGU','bhowell3@github.com');
INSERT INTO "Customer" VALUES(112,'Romance','psullivan4','4wDUDFFiWILh','ksimmons4@upenn.edu');
INSERT INTO "Customer" VALUES(113,'Romance','lspencer5','MK7qNfTan','rlarson5@wikipedia.org');
INSERT INTO "Customer" VALUES(114,'Romance','kcole6','NptUt1VL','lmoore6@qq.com');
INSERT INTO "Customer" VALUES(115,'Romance','brichards7','6srP79T0S','sjohnston7@businessweek.com');
INSERT INTO "Customer" VALUES(116,'Science','mkelley8','yiEoq4al1GC','mrichardson8@bandcamp.com');
INSERT INTO "Customer" VALUES(117,'Science','kford9','dQTSUYHT','sgray9@virginia.edu');
INSERT INTO "Customer" VALUES(118,'Science','mgomeza','2kvkNIR5scCu','nlanea@mozilla.com');
INSERT INTO "Customer" VALUES(119,'Science','kmurrayb','Czin27IpGoD','bbradleyb@google.co.uk');
INSERT INTO "Customer" VALUES(120,'Science','wtorresc','tYnUx46ml','vgordonc@cocolog-nifty.com');
INSERT INTO "Customer" VALUES(121,'Science','wgrantd','xKrKtcb2A','fmartind@ibm.com');
INSERT INTO "Customer" VALUES(122,'Home Design','ldunne','KocnrO','ssmithe@reverbnation.com');
INSERT INTO "Customer" VALUES(123,'Computer','wlynchf','qdDNTZc0tB','mbrownf@hibu.com');
INSERT INTO "Customer" VALUES(124,'Horror','rmurrayg','O6YCD0df','pdeang@networkadvertising.org');
INSERT INTO "Customer" VALUES(125,'Fantasy','dkelleyh','DqjbxKQ','klarsonh@yelp.com');
INSERT INTO "Customer" VALUES(126,'Computer','jjonesi','ZxiB4HvumYQE','bchavezi@cdbaby.com');
INSERT INTO "Customer" VALUES(127,'Fantasy','cmillsj','ESEEsi','brobertsj@photobucket.com');
