INSERT INTO "sqlite_master" VALUES('table','Address','Address',8,'CREATE TABLE "Address" ("AddressID" INTEGER PRIMARY KEY  NOT NULL , "Street" VARCHAR, "City" VARCHAR, "State" VARCHAR, "Zip" VARCHAR)');
INSERT INTO "sqlite_master" VALUES('table','Person','Person',4,'CREATE TABLE "Person" ("PersonID" INTEGER PRIMARY KEY  NOT NULL , "First" VARCHAR, "Middle" VARCHAR, "Last" VARCHAR, "AddressID" INTEGER REFERENCES "Address(AddressID)")');
INSERT INTO "sqlite_master" VALUES('table','Payment','Payment',10,'CREATE TABLE "Payment" ("Trans#" INTEGER PRIMARY KEY  NOT NULL , "Type" VARCHAR, "Amount" DOUBLE, "PersonID" INTEGER REFERENCES "Person(PersonID)")');
INSERT INTO "sqlite_master" VALUES('table','Written_By','Written_By',16,'CREATE TABLE "Written_By" ("ISBN" VARCHAR NOT NULL , "PersonID" INTEGER NOT NULL , PRIMARY KEY ("ISBN", "PersonID"), FOREIGN KEY ("ISBN") REFERENCES "Book(ISBN)", FOREIGN KEY ("PersonID") REFERENCES "Person(PersonID)")');
INSERT INTO "sqlite_master" VALUES('index','sqlite_autoindex_Written_By_1','Written_By',17,NULL);
INSERT INTO "sqlite_master" VALUES('table','Have_Purchased','Have_Purchased',18,'CREATE TABLE "Have_Purchased" ("ISBN" VARCHAR NOT NULL , "PersonID" INTEGER NOT NULL , "Qty" INTEGER, PRIMARY KEY ("ISBN", "PersonID"), FOREIGN KEY ("ISBN") REFERENCES "Book(ISBN)", FOREIGN KEY ("PersonID") REFERENCES "Person(PersonID)")');
INSERT INTO "sqlite_master" VALUES('index','sqlite_autoindex_Have_Purchased_1','Have_Purchased',19,NULL);
INSERT INTO "sqlite_master" VALUES('table','Book','Book',12,'CREATE TABLE "Book" ("ISBN" VARCHAR PRIMARY KEY  NOT NULL ,"Price" DOUBLE DEFAULT (null) ,"Year" INTEGER,"Title" VARCHAR,"Category" VARCHAR DEFAULT (null) ,"Stock" INTEGER DEFAULT (0) )');
INSERT INTO "sqlite_master" VALUES('index','sqlite_autoindex_Book_1','Book',23,NULL);
INSERT INTO "sqlite_master" VALUES('table','Author','Author',6,'CREATE TABLE "Author" ("PersonID" INTEGER PRIMARY KEY  NOT NULL ,"Favorites" INTEGER,"Rating" DOUBLE,"Birthdate" VARCHAR DEFAULT (null) )');
INSERT INTO "sqlite_master" VALUES('table','Publisher','Publisher',13,'CREATE TABLE "Publisher" ("PublisherName" VARCHAR PRIMARY KEY  NOT NULL  DEFAULT (null) ,"AddressID" INTEGER)');
INSERT INTO "sqlite_master" VALUES('index','sqlite_autoindex_Publisher_1','Publisher',7,NULL);
INSERT INTO "sqlite_master" VALUES('table','Order','Order',14,'CREATE TABLE "Order" ("OrderNumber" INTEGER PRIMARY KEY  NOT NULL  DEFAULT (null) ,"Date" DATETIME,"Trans#" INTEGER,"AddressID" INTEGER,"Status" VARCHAR)');
INSERT INTO "sqlite_master" VALUES('table','Offline','Offline',9,'CREATE TABLE "Offline" ("OrderNumber" INTEGER PRIMARY KEY  NOT NULL  DEFAULT (null) ,"Location" VARCHAR)');
INSERT INTO "sqlite_master" VALUES('table','Customer','Customer',5,'CREATE TABLE "Customer" ("PersonID" INTEGER PRIMARY KEY  NOT NULL ,"Preferences" VARCHAR,"Username" VARCHAR,"Password" VARCHAR,"EmailAddress" VARCHAR DEFAULT (null) )');
INSERT INTO "sqlite_master" VALUES('table','Published_By','Published_By',11,'CREATE TABLE "Published_By" ("PublisherName" VARCHAR NOT NULL , "ISBN" VARCHAR NOT NULL , PRIMARY KEY ("PublisherName", "ISBN"), FOREIGN KEY ("PublisherName") REFERENCES "Publisher(PublisherName)", FOREIGN KEY ("ISBN") REFERENCES "Book(ISBN)")');
INSERT INTO "sqlite_master" VALUES('index','sqlite_autoindex_Published_By_1','Published_By',15,NULL);
INSERT INTO "sqlite_master" VALUES('table','Online','Online',22,'CREATE TABLE "Online" ("OrderNumber" INTEGER PRIMARY KEY  NOT NULL  DEFAULT (null) ,"DeliveryDay" DATETIME DEFAULT (null) ,"Tracking#" INTEGER DEFAULT (null) )');
INSERT INTO "sqlite_master" VALUES('table','Order_For','Order_For',2,'CREATE TABLE "Order_For" ("ISBN" VARCHAR PRIMARY KEY  NOT NULL ,"OrderNumber" INTEGER NOT NULL  DEFAULT (null) ,"Qty" INTEGER)');
INSERT INTO "sqlite_master" VALUES('index','sqlite_autoindex_Order_For_1','Order_For',3,NULL);
