DROP TABLE IF EXISTS "Customer_Info";
CREATE TABLE "Customer_Info" ("EmailAddress" VARCHAR PRIMARY KEY  NOT NULL  DEFAULT (null) ,"Preferences" VARCHAR,"Password" VARCHAR);
INSERT INTO "Customer_Info" VALUES('mevans0@admin.ch','Literature & Fiction','vo60rgCqWDqB');
INSERT INTO "Customer_Info" VALUES('tberry1@who.int','Literature & Fiction','XLWcPBaKCAr');
INSERT INTO "Customer_Info" VALUES('jhanson2@symantec.com','Accounting & Finance','vNDCjr');
INSERT INTO "Customer_Info" VALUES('khunter3@loc.gov','Accounting & Finance','lAY6nckAGU');
INSERT INTO "Customer_Info" VALUES('mknight4@nifty.com','Romance','4wDUDFFiWILh');
INSERT INTO "Customer_Info" VALUES('adiaz5@hostgator.com','Romance','MK7qNfTan');
INSERT INTO "Customer_Info" VALUES('dmyers6@microsoft.com','Romance','NptUt1VL');
INSERT INTO "Customer_Info" VALUES('tmccoy7@t.co','Romance','6srP79T0S');
INSERT INTO "Customer_Info" VALUES('dbrown8@noaa.gov','Science','yiEoq4al1GC');
INSERT INTO "Customer_Info" VALUES('janderson9@jugem.jp','Science','dQTSUYHT');
INSERT INTO "Customer_Info" VALUES('mwheelera@wp.com','Science','2kvkNIR5scCu');
INSERT INTO "Customer_Info" VALUES('cstevensb@feedburner.com','Science','Czin27IpGoD');
INSERT INTO "Customer_Info" VALUES('jgreenc@studiopress.com','Science','tYnUx46ml');
INSERT INTO "Customer_Info" VALUES('djohnsond@apple.com','Science','xKrKtcb2A');
INSERT INTO "Customer_Info" VALUES('mduncane@mlb.com','Home Design','KocnrO');
INSERT INTO "Customer_Info" VALUES('emccoyf@ox.ac.uk','Computer','qdDNTZc0tB');
INSERT INTO "Customer_Info" VALUES('tjacobsg@ft.com','Horror','O6YCD0df');
INSERT INTO "Customer_Info" VALUES('jjonesh@zdnet.com','Fantasy','DqjbxKQ');
INSERT INTO "Customer_Info" VALUES('icruzi@microsoft.com','Computer','ZxiB4HvumYQE');
INSERT INTO "Customer_Info" VALUES('crosej@goo.ne.jp','Fantasy','ESEEsi');
INSERT INTO "Customer_Info" VALUES('pjonesk@cbsnews.com','Literature & Fiction','vo60rgCqWDqB');
INSERT INTO "Customer_Info" VALUES('dfloresl@paginegialle.it','Literature & Fiction','XLWcPBaKCAr');
INSERT INTO "Customer_Info" VALUES('nalexanderm@sohu.com','Accounting & Finance','vNDCjr');
INSERT INTO "Customer_Info" VALUES('abryantn@epa.gov','Accounting & Finance','lAY6nckAGU');
INSERT INTO "Customer_Info" VALUES('slopezo@parallels.com','Romance','4wDUDFFiWILh');
INSERT INTO "Customer_Info" VALUES('aramosp@ftc.gov','Romance','MK7qNfTan');
INSERT INTO "Customer_Info" VALUES('cmoralesq@cmu.edu','Romance','NptUt1VL');
INSERT INTO "Customer_Info" VALUES('mwagnerr@adobe.com','Romance','6srP79T0S');
INSERT INTO "Customer_Info" VALUES('dreyess@instagram.com','Science','yiEoq4al1GC');
INSERT INTO "Customer_Info" VALUES('cgordont@adobe.com','Science','dQTSUYHT');
INSERT INTO "Customer_Info" VALUES('jwarrenu@pinterest.com','Science','2kvkNIR5scCu');
INSERT INTO "Customer_Info" VALUES('kcooperv@furl.net','Science','Czin27IpGoD');
INSERT INTO "Customer_Info" VALUES('mshaww@exblog.jp','Science','tYnUx46ml');
INSERT INTO "Customer_Info" VALUES('lknightx@twitpic.com','Science','xKrKtcb2A');
INSERT INTO "Customer_Info" VALUES('jgutierrezy@drupal.org','Home Design','KocnrO');
INSERT INTO "Customer_Info" VALUES('rriveraz@disqus.com','Computer','qdDNTZc0tB');
INSERT INTO "Customer_Info" VALUES('pcole10@dagondesign.com','Horror','O6YCD0df');
INSERT INTO "Customer_Info" VALUES('rhamilton11@tumblr.com','Fantasy','DqjbxKQ');
INSERT INTO "Customer_Info" VALUES('jstanley12@rakuten.co.jp','Computer','ZxiB4HvumYQE');
INSERT INTO "Customer_Info" VALUES('aruiz13@bandcamp.com','Fantasy','ESEEsi');
INSERT INTO "Customer_Info" VALUES('mgray14@ask.com','Literature & Fiction','vo60rgCqWDqB');
INSERT INTO "Customer_Info" VALUES('jstanley15@cmu.edu','Literature & Fiction','XLWcPBaKCAr');
INSERT INTO "Customer_Info" VALUES('drobinson16@hatena.ne.jp','Accounting & Finance','vNDCjr');
INSERT INTO "Customer_Info" VALUES('kgarrett17@slashdot.org','Accounting & Finance','lAY6nckAGU');
INSERT INTO "Customer_Info" VALUES('jross18@delicious.com','Romance','4wDUDFFiWILh');
INSERT INTO "Customer_Info" VALUES('bromero19@seesaa.net','Romance','MK7qNfTan');
INSERT INTO "Customer_Info" VALUES('cwest1a@tinypic.com','Romance','NptUt1VL');
INSERT INTO "Customer_Info" VALUES('kporter1b@npr.org','Romance','6srP79T0S');
INSERT INTO "Customer_Info" VALUES('mferguson1c@senate.gov','Science','yiEoq4al1GC');
INSERT INTO "Customer_Info" VALUES('bjohnston1d@comsenz.com','Science','dQTSUYHT');
INSERT INTO "Customer_Info" VALUES('rcarpenter1e@tamu.edu','Science','2kvkNIR5scCu');
INSERT INTO "Customer_Info" VALUES('eford1f@netscape.com','Science','Czin27IpGoD');
INSERT INTO "Customer_Info" VALUES('jrussell1g@cbslocal.com','Science','tYnUx46ml');
INSERT INTO "Customer_Info" VALUES('scruz1h@scribd.com','Science','xKrKtcb2A');
INSERT INTO "Customer_Info" VALUES('lyoung1i@shutterfly.com','Home Design','KocnrO');
INSERT INTO "Customer_Info" VALUES('mpierce1j@icq.com','Computer','qdDNTZc0tB');
INSERT INTO "Customer_Info" VALUES('chenderson1k@facebook.com','Horror','O6YCD0df');
INSERT INTO "Customer_Info" VALUES('kpeterson1l@eventbrite.com','Fantasy','DqjbxKQ');
INSERT INTO "Customer_Info" VALUES('rward1m@un.org','Computer','ZxiB4HvumYQE');
INSERT INTO "Customer_Info" VALUES('tcarr1n@hp.com','Fantasy','ESEEsi');
INSERT INTO "Customer_Info" VALUES('sperry1o@marriott.com','Literature & Fiction','vo60rgCqWDqB');
INSERT INTO "Customer_Info" VALUES('salexander1p@surveymonkey.com','Literature & Fiction','XLWcPBaKCAr');
INSERT INTO "Customer_Info" VALUES('jcooper1q@creativecommons.org','Accounting & Finance','vNDCjr');
INSERT INTO "Customer_Info" VALUES('anelson1r@about.com','Accounting & Finance','lAY6nckAGU');
INSERT INTO "Customer_Info" VALUES('rjordan1s@hc360.com','Romance','4wDUDFFiWILh');
INSERT INTO "Customer_Info" VALUES('dgreene1t@tamu.edu','Romance','MK7qNfTan');
INSERT INTO "Customer_Info" VALUES('jlarson1u@earthlink.net','Romance','NptUt1VL');
INSERT INTO "Customer_Info" VALUES('pjames1v@prnewswire.com','Romance','6srP79T0S');
INSERT INTO "Customer_Info" VALUES('sday1w@theguardian.com','Science','yiEoq4al1GC');
INSERT INTO "Customer_Info" VALUES('sarmstrong1x@examiner.com','Science','dQTSUYHT');
INSERT INTO "Customer_Info" VALUES('ssmith1y@huffingtonpost.com','Science','2kvkNIR5scCu');
INSERT INTO "Customer_Info" VALUES('dwebb1z@sciencedirect.com','Science','Czin27IpGoD');
INSERT INTO "Customer_Info" VALUES('ssimmons20@vkontakte.ru','Science','tYnUx46ml');
INSERT INTO "Customer_Info" VALUES('pnelson21@buzzfeed.com','Science','xKrKtcb2A');
INSERT INTO "Customer_Info" VALUES('krivera22@icio.us','Home Design','KocnrO');
INSERT INTO "Customer_Info" VALUES('jadams23@skype.com','Computer','qdDNTZc0tB');
INSERT INTO "Customer_Info" VALUES('slarson24@howstuffworks.com','Horror','O6YCD0df');
INSERT INTO "Customer_Info" VALUES('dreyes25@ucoz.ru','Fantasy','DqjbxKQ');
INSERT INTO "Customer_Info" VALUES('gday26@google.com.au','Computer','ZxiB4HvumYQE');
INSERT INTO "Customer_Info" VALUES('lfreeman27@hugedomains.com','Fantasy','ESEEsi');
INSERT INTO "Customer_Info" VALUES('mbishop28@e-recht24.de','Literature & Fiction','vo60rgCqWDqB');
INSERT INTO "Customer_Info" VALUES('kryan29@skype.com','Literature & Fiction','XLWcPBaKCAr');
INSERT INTO "Customer_Info" VALUES('jwelch2a@mtv.com','Accounting & Finance','vNDCjr');
INSERT INTO "Customer_Info" VALUES('wmurray2b@biblegateway.com','Accounting & Finance','lAY6nckAGU');
INSERT INTO "Customer_Info" VALUES('lhicks2c@pcworld.com','Romance','4wDUDFFiWILh');
INSERT INTO "Customer_Info" VALUES('msullivan2d@nydailynews.com','Romance','MK7qNfTan');
INSERT INTO "Customer_Info" VALUES('kward2e@blogger.com','Romance','NptUt1VL');
INSERT INTO "Customer_Info" VALUES('rday2f@issuu.com','Romance','6srP79T0S');
INSERT INTO "Customer_Info" VALUES('dsanchez2g@4shared.com','Science','yiEoq4al1GC');
INSERT INTO "Customer_Info" VALUES('kday2h@salon.com','Science','dQTSUYHT');
INSERT INTO "Customer_Info" VALUES('hreynolds2i@gnu.org','Science','2kvkNIR5scCu');
INSERT INTO "Customer_Info" VALUES('dmcdonald2j@bloglines.com','Science','Czin27IpGoD');
INSERT INTO "Customer_Info" VALUES('creynolds2k@feedburner.com','Science','tYnUx46ml');
INSERT INTO "Customer_Info" VALUES('aramos2l@bloomberg.com','Science','xKrKtcb2A');
INSERT INTO "Customer_Info" VALUES('fcunningham2m@imdb.com','Home Design','KocnrO');
INSERT INTO "Customer_Info" VALUES('krivera2n@telegraph.co.uk','Computer','qdDNTZc0tB');
INSERT INTO "Customer_Info" VALUES('amartinez2o@ucsd.edu','Horror','O6YCD0df');
INSERT INTO "Customer_Info" VALUES('emason2p@quantcast.com','Fantasy','DqjbxKQ');
INSERT INTO "Customer_Info" VALUES('rfowler2q@ning.com','Computer','ZxiB4HvumYQE');
INSERT INTO "Customer_Info" VALUES('fowens2r@vimeo.com','Fantasy','ESEEsi');
INSERT INTO "Customer_Info" VALUES('cwoods2s@is.gd','Literature & Fiction','vo60rgCqWDqB');
INSERT INTO "Customer_Info" VALUES('rhicks2t@yellowpages.com','Literature & Fiction','XLWcPBaKCAr');
INSERT INTO "Customer_Info" VALUES('mbennett2u@delicious.com','Accounting & Finance','vNDCjr');
INSERT INTO "Customer_Info" VALUES('akim2v@addtoany.com','Accounting & Finance','lAY6nckAGU');
INSERT INTO "Customer_Info" VALUES('hwright2w@1688.com','Romance','4wDUDFFiWILh');
INSERT INTO "Customer_Info" VALUES('scarr2x@ning.com','Romance','MK7qNfTan');
INSERT INTO "Customer_Info" VALUES('nthompson2y@weebly.com','Romance','NptUt1VL');
INSERT INTO "Customer_Info" VALUES('vstevens2z@usgs.gov','Literature & Fiction','vo60rgCqWDqB');
INSERT INTO "Customer_Info" VALUES('dclark30@youku.com','Literature & Fiction','XLWcPBaKCAr');
INSERT INTO "Customer_Info" VALUES('lberry31@hc360.com','Accounting & Finance','vNDCjr');
INSERT INTO "Customer_Info" VALUES('plong32@washington.edu','Accounting & Finance','lAY6nckAGU');
INSERT INTO "Customer_Info" VALUES('bcunningham33@youtube.com','Romance','4wDUDFFiWILh');
INSERT INTO "Customer_Info" VALUES('hlane34@domainmarket.com','Romance','MK7qNfTan');
INSERT INTO "Customer_Info" VALUES('bpayne35@domainmarket.com','Romance','NptUt1VL');
INSERT INTO "Customer_Info" VALUES('bcastillo36@home.pl','Romance','6srP79T0S');
INSERT INTO "Customer_Info" VALUES('rmontgomery37@hugedomains.com','Science','yiEoq4al1GC');
INSERT INTO "Customer_Info" VALUES('jford38@unblog.fr','Science','dQTSUYHT');
INSERT INTO "Customer_Info" VALUES('sberry39@reference.com','Science','2kvkNIR5scCu');
INSERT INTO "Customer_Info" VALUES('dhudson3a@naver.com','Science','Czin27IpGoD');
INSERT INTO "Customer_Info" VALUES('jrichards3b@domainmarket.com','Science','tYnUx46ml');
INSERT INTO "Customer_Info" VALUES('fkim3c@comcast.net','Science','xKrKtcb2A');
INSERT INTO "Customer_Info" VALUES('sporter3d@buzzfeed.com','Home Design','KocnrO');
INSERT INTO "Customer_Info" VALUES('ssanchez3e@latimes.com','Computer','qdDNTZc0tB');
INSERT INTO "Customer_Info" VALUES('wmontgomery3f@freewebs.com','Horror','O6YCD0df');
INSERT INTO "Customer_Info" VALUES('elarson3g@altervista.org','Fantasy','DqjbxKQ');
INSERT INTO "Customer_Info" VALUES('ljohnson3h@prweb.com','Computer','ZxiB4HvumYQE');
INSERT INTO "Customer_Info" VALUES('jkim3i@reddit.com','Fantasy','ESEEsi');
