DROP TABLE IF EXISTS "Customer";
CREATE TABLE "Customer" ("PersonID" INTEGER PRIMARY KEY  NOT NULL ,"Preferences" VARCHAR,"Username" VARCHAR,"Password" VARCHAR,"EmailAddress" VARCHAR DEFAULT (null), FOREIGN KEY ("PersonID") REFERENCES "Person(PersonID)" );
INSERT INTO "Customer" VALUES(1,'Literature & Fiction','pmurphy0','vo60rgCqWDqB','ahoward0@eepurl.com');
INSERT INTO "Customer" VALUES(2,'Literature & Fiction','anichols1','XLWcPBaKCAr','rperry1@bbb.org');
INSERT INTO "Customer" VALUES(3,'Accounting & Finance','greed2','vNDCjr','nlopez2@independent.co.uk');
INSERT INTO "Customer" VALUES(4,'Accounting & Finance','rbanks3','lAY6nckAGU','bhowell3@github.com');
INSERT INTO "Customer" VALUES(5,'Romance','psullivan4','4wDUDFFiWILh','ksimmons4@upenn.edu');
INSERT INTO "Customer" VALUES(6,'Romance','lspencer5','MK7qNfTan','rlarson5@wikipedia.org');
INSERT INTO "Customer" VALUES(7,'Romance','kcole6','NptUt1VL','lmoore6@qq.com');
INSERT INTO "Customer" VALUES(8,'Romance','brichards7','6srP79T0S','sjohnston7@businessweek.com');
INSERT INTO "Customer" VALUES(9,'Science','mkelley8','yiEoq4al1GC','mrichardson8@bandcamp.com');
INSERT INTO "Customer" VALUES(10,'Science','kford9','dQTSUYHT','sgray9@virginia.edu');
INSERT INTO "Customer" VALUES(11,'Science','mgomeza','2kvkNIR5scCu','nlanea@mozilla.com');
INSERT INTO "Customer" VALUES(12,'Science','kmurrayb','Czin27IpGoD','bbradleyb@google.co.uk');
INSERT INTO "Customer" VALUES(13,'Science','wtorresc','tYnUx46ml','vgordonc@cocolog-nifty.com');
INSERT INTO "Customer" VALUES(14,'Science','wgrantd','xKrKtcb2A','fmartind@ibm.com');
INSERT INTO "Customer" VALUES(15,'Home Design','ldunne','KocnrO','ssmithe@reverbnation.com');
INSERT INTO "Customer" VALUES(16,'Computer','wlynchf','qdDNTZc0tB','mbrownf@hibu.com');
INSERT INTO "Customer" VALUES(17,'Horror','rmurrayg','O6YCD0df','pdeang@networkadvertising.org');
INSERT INTO "Customer" VALUES(18,'Fantasy','dkelleyh','DqjbxKQ','klarsonh@yelp.com');
INSERT INTO "Customer" VALUES(19,'Computer','jjonesi','ZxiB4HvumYQE','bchavezi@cdbaby.com');
INSERT INTO "Customer" VALUES(20,'Fantasy','cmillsj','ESEEsi','brobertsj@photobucket.com');
INSERT INTO "Customer" VALUES(21,'Literature & Fiction','pmurphy0','vo60rgCqWDqB','ahoward0@eepurl.com');
INSERT INTO "Customer" VALUES(22,'Literature & Fiction','anichols1','XLWcPBaKCAr','rperry1@bbb.org');
INSERT INTO "Customer" VALUES(23,'Accounting & Finance','greed2','vNDCjr','nlopez2@independent.co.uk');
INSERT INTO "Customer" VALUES(24,'Accounting & Finance','rbanks3','lAY6nckAGU','bhowell3@github.com');
INSERT INTO "Customer" VALUES(25,'Romance','psullivan4','4wDUDFFiWILh','ksimmons4@upenn.edu');
INSERT INTO "Customer" VALUES(26,'Romance','lspencer5','MK7qNfTan','rlarson5@wikipedia.org');
INSERT INTO "Customer" VALUES(27,'Romance','kcole6','NptUt1VL','lmoore6@qq.com');
INSERT INTO "Customer" VALUES(28,'Romance','brichards7','6srP79T0S','sjohnston7@businessweek.com');
INSERT INTO "Customer" VALUES(29,'Science','mkelley8','yiEoq4al1GC','mrichardson8@bandcamp.com');
INSERT INTO "Customer" VALUES(30,'Science','kford9','dQTSUYHT','sgray9@virginia.edu');
INSERT INTO "Customer" VALUES(31,'Science','mgomeza','2kvkNIR5scCu','nlanea@mozilla.com');
INSERT INTO "Customer" VALUES(32,'Science','kmurrayb','Czin27IpGoD','bbradleyb@google.co.uk');
INSERT INTO "Customer" VALUES(33,'Science','wtorresc','tYnUx46ml','vgordonc@cocolog-nifty.com');
INSERT INTO "Customer" VALUES(34,'Science','wgrantd','xKrKtcb2A','fmartind@ibm.com');
INSERT INTO "Customer" VALUES(35,'Home Design','ldunne','KocnrO','ssmithe@reverbnation.com');
INSERT INTO "Customer" VALUES(36,'Computer','wlynchf','qdDNTZc0tB','mbrownf@hibu.com');
INSERT INTO "Customer" VALUES(37,'Horror','rmurrayg','O6YCD0df','pdeang@networkadvertising.org');
INSERT INTO "Customer" VALUES(38,'Fantasy','dkelleyh','DqjbxKQ','klarsonh@yelp.com');
INSERT INTO "Customer" VALUES(39,'Computer','jjonesi','ZxiB4HvumYQE','bchavezi@cdbaby.com');
INSERT INTO "Customer" VALUES(40,'Fantasy','cmillsj','ESEEsi','brobertsj@photobucket.com');
INSERT INTO "Customer" VALUES(41,'Literature & Fiction','pmurphy0','vo60rgCqWDqB','ahoward0@eepurl.com');
INSERT INTO "Customer" VALUES(42,'Literature & Fiction','anichols1','XLWcPBaKCAr','rperry1@bbb.org');
INSERT INTO "Customer" VALUES(43,'Accounting & Finance','greed2','vNDCjr','nlopez2@independent.co.uk');
INSERT INTO "Customer" VALUES(44,'Accounting & Finance','rbanks3','lAY6nckAGU','bhowell3@github.com');
INSERT INTO "Customer" VALUES(45,'Romance','psullivan4','4wDUDFFiWILh','ksimmons4@upenn.edu');
INSERT INTO "Customer" VALUES(46,'Romance','lspencer5','MK7qNfTan','rlarson5@wikipedia.org');
INSERT INTO "Customer" VALUES(47,'Romance','kcole6','NptUt1VL','lmoore6@qq.com');
INSERT INTO "Customer" VALUES(48,'Romance','brichards7','6srP79T0S','sjohnston7@businessweek.com');
INSERT INTO "Customer" VALUES(49,'Science','mkelley8','yiEoq4al1GC','mrichardson8@bandcamp.com');
INSERT INTO "Customer" VALUES(50,'Science','kford9','dQTSUYHT','sgray9@virginia.edu');
INSERT INTO "Customer" VALUES(51,'Science','mgomeza','2kvkNIR5scCu','nlanea@mozilla.com');
INSERT INTO "Customer" VALUES(52,'Science','kmurrayb','Czin27IpGoD','bbradleyb@google.co.uk');
INSERT INTO "Customer" VALUES(53,'Science','wtorresc','tYnUx46ml','vgordonc@cocolog-nifty.com');
INSERT INTO "Customer" VALUES(54,'Science','wgrantd','xKrKtcb2A','fmartind@ibm.com');
INSERT INTO "Customer" VALUES(55,'Home Design','ldunne','KocnrO','ssmithe@reverbnation.com');
INSERT INTO "Customer" VALUES(56,'Computer','wlynchf','qdDNTZc0tB','mbrownf@hibu.com');
INSERT INTO "Customer" VALUES(57,'Horror','rmurrayg','O6YCD0df','pdeang@networkadvertising.org');
INSERT INTO "Customer" VALUES(58,'Fantasy','dkelleyh','DqjbxKQ','klarsonh@yelp.com');
INSERT INTO "Customer" VALUES(59,'Computer','jjonesi','ZxiB4HvumYQE','bchavezi@cdbaby.com');
INSERT INTO "Customer" VALUES(60,'Fantasy','cmillsj','ESEEsi','brobertsj@photobucket.com');
INSERT INTO "Customer" VALUES(61,'Literature & Fiction','pmurphy0','vo60rgCqWDqB','ahoward0@eepurl.com');
INSERT INTO "Customer" VALUES(62,'Literature & Fiction','anichols1','XLWcPBaKCAr','rperry1@bbb.org');
INSERT INTO "Customer" VALUES(63,'Accounting & Finance','greed2','vNDCjr','nlopez2@independent.co.uk');
INSERT INTO "Customer" VALUES(64,'Accounting & Finance','rbanks3','lAY6nckAGU','bhowell3@github.com');
INSERT INTO "Customer" VALUES(65,'Romance','psullivan4','4wDUDFFiWILh','ksimmons4@upenn.edu');
INSERT INTO "Customer" VALUES(66,'Romance','lspencer5','MK7qNfTan','rlarson5@wikipedia.org');
INSERT INTO "Customer" VALUES(67,'Romance','kcole6','NptUt1VL','lmoore6@qq.com');
INSERT INTO "Customer" VALUES(68,'Romance','brichards7','6srP79T0S','sjohnston7@businessweek.com');
INSERT INTO "Customer" VALUES(69,'Science','mkelley8','yiEoq4al1GC','mrichardson8@bandcamp.com');
INSERT INTO "Customer" VALUES(70,'Science','kford9','dQTSUYHT','sgray9@virginia.edu');
INSERT INTO "Customer" VALUES(71,'Science','mgomeza','2kvkNIR5scCu','nlanea@mozilla.com');
INSERT INTO "Customer" VALUES(72,'Science','kmurrayb','Czin27IpGoD','bbradleyb@google.co.uk');
INSERT INTO "Customer" VALUES(73,'Science','wtorresc','tYnUx46ml','vgordonc@cocolog-nifty.com');
INSERT INTO "Customer" VALUES(74,'Science','wgrantd','xKrKtcb2A','fmartind@ibm.com');
INSERT INTO "Customer" VALUES(75,'Home Design','ldunne','KocnrO','ssmithe@reverbnation.com');
INSERT INTO "Customer" VALUES(76,'Computer','wlynchf','qdDNTZc0tB','mbrownf@hibu.com');
INSERT INTO "Customer" VALUES(77,'Horror','rmurrayg','O6YCD0df','pdeang@networkadvertising.org');
INSERT INTO "Customer" VALUES(78,'Fantasy','dkelleyh','DqjbxKQ','klarsonh@yelp.com');
INSERT INTO "Customer" VALUES(79,'Computer','jjonesi','ZxiB4HvumYQE','bchavezi@cdbaby.com');
INSERT INTO "Customer" VALUES(80,'Fantasy','cmillsj','ESEEsi','brobertsj@photobucket.com');
INSERT INTO "Customer" VALUES(81,'Literature & Fiction','pmurphy0','vo60rgCqWDqB','ahoward0@eepurl.com');
INSERT INTO "Customer" VALUES(82,'Literature & Fiction','anichols1','XLWcPBaKCAr','rperry1@bbb.org');
INSERT INTO "Customer" VALUES(83,'Accounting & Finance','greed2','vNDCjr','nlopez2@independent.co.uk');
INSERT INTO "Customer" VALUES(84,'Accounting & Finance','rbanks3','lAY6nckAGU','bhowell3@github.com');
INSERT INTO "Customer" VALUES(85,'Romance','psullivan4','4wDUDFFiWILh','ksimmons4@upenn.edu');
INSERT INTO "Customer" VALUES(86,'Romance','lspencer5','MK7qNfTan','rlarson5@wikipedia.org');
INSERT INTO "Customer" VALUES(87,'Romance','kcole6','NptUt1VL','lmoore6@qq.com');
INSERT INTO "Customer" VALUES(88,'Romance','brichards7','6srP79T0S','sjohnston7@businessweek.com');
INSERT INTO "Customer" VALUES(89,'Science','mkelley8','yiEoq4al1GC','mrichardson8@bandcamp.com');
INSERT INTO "Customer" VALUES(90,'Science','kford9','dQTSUYHT','sgray9@virginia.edu');
INSERT INTO "Customer" VALUES(91,'Science','mgomeza','2kvkNIR5scCu','nlanea@mozilla.com');
INSERT INTO "Customer" VALUES(92,'Science','kmurrayb','Czin27IpGoD','bbradleyb@google.co.uk');
INSERT INTO "Customer" VALUES(93,'Science','wtorresc','tYnUx46ml','vgordonc@cocolog-nifty.com');
INSERT INTO "Customer" VALUES(94,'Science','wgrantd','xKrKtcb2A','fmartind@ibm.com');
INSERT INTO "Customer" VALUES(95,'Home Design','ldunne','KocnrO','ssmithe@reverbnation.com');
INSERT INTO "Customer" VALUES(96,'Computer','wlynchf','qdDNTZc0tB','mbrownf@hibu.com');
INSERT INTO "Customer" VALUES(97,'Horror','rmurrayg','O6YCD0df','pdeang@networkadvertising.org');
INSERT INTO "Customer" VALUES(98,'Fantasy','dkelleyh','DqjbxKQ','klarsonh@yelp.com');
INSERT INTO "Customer" VALUES(99,'Computer','jjonesi','ZxiB4HvumYQE','bchavezi@cdbaby.com');
INSERT INTO "Customer" VALUES(100,'Fantasy','cmillsj','ESEEsi','brobertsj@photobucket.com');
INSERT INTO "Customer" VALUES(101,'Literature & Fiction','pmurphy0','vo60rgCqWDqB','ahoward0@eepurl.com');
INSERT INTO "Customer" VALUES(102,'Literature & Fiction','anichols1','XLWcPBaKCAr','rperry1@bbb.org');
INSERT INTO "Customer" VALUES(103,'Accounting & Finance','greed2','vNDCjr','nlopez2@independent.co.uk');
INSERT INTO "Customer" VALUES(104,'Accounting & Finance','rbanks3','lAY6nckAGU','bhowell3@github.com');
INSERT INTO "Customer" VALUES(105,'Romance','psullivan4','4wDUDFFiWILh','ksimmons4@upenn.edu');
INSERT INTO "Customer" VALUES(106,'Romance','lspencer5','MK7qNfTan','rlarson5@wikipedia.org');
INSERT INTO "Customer" VALUES(107,'Romance','kcole6','NptUt1VL','lmoore6@qq.com');
INSERT INTO "Customer" VALUES(108,'Literature & Fiction','pmurphy0','vo60rgCqWDqB','ahoward0@eepurl.com');
INSERT INTO "Customer" VALUES(109,'Literature & Fiction','anichols1','XLWcPBaKCAr','rperry1@bbb.org');
INSERT INTO "Customer" VALUES(110,'Accounting & Finance','greed2','vNDCjr','nlopez2@independent.co.uk');
INSERT INTO "Customer" VALUES(111,'Accounting & Finance','rbanks3','lAY6nckAGU','bhowell3@github.com');
INSERT INTO "Customer" VALUES(112,'Romance','psullivan4','4wDUDFFiWILh','ksimmons4@upenn.edu');
INSERT INTO "Customer" VALUES(113,'Romance','lspencer5','MK7qNfTan','rlarson5@wikipedia.org');
INSERT INTO "Customer" VALUES(114,'Romance','kcole6','NptUt1VL','lmoore6@qq.com');
INSERT INTO "Customer" VALUES(115,'Romance','brichards7','6srP79T0S','sjohnston7@businessweek.com');
INSERT INTO "Customer" VALUES(116,'Science','mkelley8','yiEoq4al1GC','mrichardson8@bandcamp.com');
INSERT INTO "Customer" VALUES(117,'Science','kford9','dQTSUYHT','sgray9@virginia.edu');
INSERT INTO "Customer" VALUES(118,'Science','mgomeza','2kvkNIR5scCu','nlanea@mozilla.com');
INSERT INTO "Customer" VALUES(119,'Science','kmurrayb','Czin27IpGoD','bbradleyb@google.co.uk');
INSERT INTO "Customer" VALUES(120,'Science','wtorresc','tYnUx46ml','vgordonc@cocolog-nifty.com');
INSERT INTO "Customer" VALUES(121,'Science','wgrantd','xKrKtcb2A','fmartind@ibm.com');
INSERT INTO "Customer" VALUES(122,'Home Design','ldunne','KocnrO','ssmithe@reverbnation.com');
INSERT INTO "Customer" VALUES(123,'Computer','wlynchf','qdDNTZc0tB','mbrownf@hibu.com');
INSERT INTO "Customer" VALUES(124,'Horror','rmurrayg','O6YCD0df','pdeang@networkadvertising.org');
INSERT INTO "Customer" VALUES(125,'Fantasy','dkelleyh','DqjbxKQ','klarsonh@yelp.com');
INSERT INTO "Customer" VALUES(126,'Computer','jjonesi','ZxiB4HvumYQE','bchavezi@cdbaby.com');
INSERT INTO "Customer" VALUES(127,'Fantasy','cmillsj','ESEEsi','brobertsj@photobucket.com');
