DROP TABLE IF EXISTS "Offline";
CREATE TABLE "Offline" ("OrderNumber" INTEGER PRIMARY KEY  NOT NULL  DEFAULT (null) ,"Location" VARCHAR, FOREIGN KEY ("OrderNumber") REFERENCES "Order(OrderNumber)" );
INSERT INTO "Offline" VALUES(21,'Charleston, West Virginia');
INSERT INTO "Offline" VALUES(22,'Little Rock, Arkansas');
INSERT INTO "Offline" VALUES(23,'San Francisco, California');
INSERT INTO "Offline" VALUES(24,'Spring, Texas');
INSERT INTO "Offline" VALUES(25,'Lansing, Michigan');
INSERT INTO "Offline" VALUES(26,'Minneapolis, Minnesota');
INSERT INTO "Offline" VALUES(27,'Johnstown, Pennsylvania');
INSERT INTO "Offline" VALUES(28,'Van Nuys, California');
INSERT INTO "Offline" VALUES(29,'San Francisco, California');
INSERT INTO "Offline" VALUES(30,'Minneapolis, Minnesota');
INSERT INTO "Offline" VALUES(31,'Scottsdale, Arizona');
INSERT INTO "Offline" VALUES(32,'Seminole, Florida');
INSERT INTO "Offline" VALUES(33,'Murfreesboro, Tennessee');
INSERT INTO "Offline" VALUES(34,'Austin, Texas');
INSERT INTO "Offline" VALUES(35,'Buffalo, New York');
INSERT INTO "Offline" VALUES(36,'Carson City, Nevada');
INSERT INTO "Offline" VALUES(37,'El Paso, Texas');
INSERT INTO "Offline" VALUES(38,'Chula Vista, California');
INSERT INTO "Offline" VALUES(39,'El Paso, Texas');
INSERT INTO "Offline" VALUES(40,'Youngstown, Ohio');
